
spring:
  application:
    name: prom-v2-dbi-service

server:
  port: ${EUREKA_REGISTRATION_PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:2011/eureka}
  instance:
    preferIpAddress: true